apiVersion: apps/v1
kind: Deployment
metadata:
  name: tfb-qrh-sample-0
  labels:
    app: tfb-qrh-app-0
spec:
  replicas: 1
  selector:
   matchLabels:
     app: tfb-qrh-deployment
  template:
    metadata:
      labels:
        name: tfb-qrh-deployment
        app: tfb-qrh-deployment
        # Add label to the application which is used by kruize/autotune to monitor it
        app.kubernetes.io/name: "tfb-qrh-deployment"
        app.kubernetes.io/layer: "quarkus"
        version: v1
    spec:
      volumes:
      - name: test-volume
      containers:
      - name: tfb-server
        image: kruize/tfb-qrh:1.13.2.F_mm.v1
        imagePullPolicy: IfNotPresent
        env:
          - name: "JAVA_OPTIONS"
            value: " -XX:+TieredCompilation -XX:-AllowParallelDefineClass -XX:+AllowVectorizeOnDemand -XX:+AlwaysCompileLoopMethods -XX:+AlwaysPreTouch -XX:-AlwaysTenure -XX:+BackgroundCompilation -XX:+DoEscapeAnalysis -XX:-UseInlineCaches -XX:-UseLoopPredicate -XX:-UseStringDeduplication -XX:+UseSuperWord -XX:+UseTypeSpeculation -XX:FreqInlineSize=382 -XX:MaxInlineLevel=13 -XX:MinInliningThreshold=299 -XX:CompileThreshold=17011 -XX:CompileThresholdScaling=8.81 -XX:ConcGCThreads=5 -XX:InlineSmallCode=2915 -XX:LoopUnrollLimit=78 -XX:LoopUnrollMin=0 -XX:MinSurvivorRatio=36 -XX:NewRatio=18 -XX:TieredStopAtLevel=1 -Dquarkus.thread-pool.core-threads=20 -Dquarkus.thread-pool.queue-size=605 -Dquarkus.datasource.jdbc.min-size=2 -Dquarkus.datasource.jdbc.max-size=45" 
        ports:
          - containerPort: 8080
        resources:
         requests:
          cpu: 2.8200000000000003
          memory: 1024M
         limits:
          cpu: 2.8200000000000003
          memory: 1024M
        volumeMounts:
          - name: "test-volume"
            mountPath: "/opt/jLogs"
---
apiVersion: v1
kind: Service
metadata:
  name: tfb-qrh-service-0
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/q/metrics'
  labels:
    app: tfb-qrh-app-0
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 32334
      targetPort: 8080
      name: tfb-qrh-port-0
  selector:
    name: tfb-qrh-deployment
