apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tfb-qrh
  labels:
    team: tfb-qrh-frontend
spec:
  selector:
    matchLabels:
        app: tfb-qrh-app
  endpoints:
    - port: tfb-qrh-port
      path: '/q/metrics'
